---

- name: Install docker engine on Debian
  hosts: localhost
  become: true
  tasks:

  - name: Install requirements packages
    apt:
      name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      state: latest
      update_cache: yes

  - name: Add docker’s official GPG key
    shell: curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --batch --yes --dearmor -o /usr/share/keyrings/docker.gpg

  - name: Set up the repository
    shell: echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/debian
           $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

  - name: Update the package index and install docker components
    apt:
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      update_cache: yes